// QUESTION NO: 01

let username;

// QUESTION NO: 02

let myName = ("Maryam");

//QUESTION NO: 03 

let titledMessage;
 titledMessage = ("Hello World");
alert("titleMessage");

// QUESTION NO: 04 

let fullName = ("Ayesha");
let studentsAge = ("20");
let  studentsQualification = ("Undergraduation");
let studentsRollNo = ("WMA-122426");

alert("fullName");
alert("studentsAge");
alert("studentsQualification");
alert("studentsRollNo");

// QUESTION NO: 05

let pizza = ("PIZZA/nPIZZ/nPIZ/nPI/nP");
alert("PIZZA");

// QUESTION NO: 06 

let myEmail = ("maryaamalii@gmail.com");
alert("My Email address is " + "maryaamalii@gmail.com");

// QUESTION NO: 07

let theBook = ("A smarter way to learn JavaScript");
alert("I am trying to learn from the book A smarter \n way to learn JavaScript");

// QUESTION NO: 08

let pattern;
pattern = ("▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ஜ۩۞۩ஜ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬");
alert ("pattern");

